---
# tasks file for docker

- name: Install packages
  yum: name={{ item }} state=present
  with_items:
    - curl
    - git
    - python-pip
  sudo: yes

- name: Install Docker
  yum: name=docker-ce state=present

- name: Create docker config dir
  file: name=/etc/docker/ state=directory

- name: generate Docker config file
  template: src=daemon.json dest=/etc/docker/daemon.json

- name: Start Docker on boot
  systemd: name=docker state=started enabled=yes

- name: Install Python packages
  pip: name=docker state=present
