---
# tasks file for server

- name: Install packages
  apt: pkg={{ item }} state=present
  with_items:
    - python-minimal
    - python-dev
    - python-pip
    - python3
    - python3-pip
    - python3-dev
    - nginx
    - ssh
    - vim
    - supervisor
    - git
    - gettext
    - libffi-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libjpeg8-dev
    - zlib1g-dev
  sudo: yes
