---
# tasks file for server

- name: stop nginx
  systemd: name=nginx state=stopped

- name: remove nginx enable project symlink
  file: name={{ nginx.remote_nginx_enable_dir }}/default state=absent
  ignore_errors: True

- name: remove nginx enable project symlink
  file: name={{ nginx.remote_nginx_enable_dir }}/{{ project_name }} state=absent

- name: remove nginx avaliable project config file
  file: name={{ nginx.remote_nginx_avail_dir }}/* state=absent

- name: generate nginx project config file
  template: src=nginx.conf.tmp dest={{ nginx.remote_nginx_avail_dir }}/{{ project_name }}

- name: create symlink
  file: src={{ nginx.remote_nginx_avail_dir }}/{{ project_name }} dest={{ nginx.remote_nginx_enable_dir }}/{{ project_name }} state=link

- name: copy db
  shell: cp src/mysite/demo.sqlite3 src/mysite/production.sqlite3
  args:
    chdir: "{{ remote_app_dir }}/{{ project_name }}"

- name: restart nginx
  systemd: name=nginx state=started
