---
# tasks file for server
- name: replace source_list
  template: src=sources.list dest=/etc/apt/

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=600
  sudo: yes

- name: Update apt
  raw: apt-get update
  sudo: yes
